### PR TITLE
feat: change hero image for winter

### PR DESCRIPTION
**Pull request by paulstey**
This is a baby PR that changes the hero image to a Winter Wonderland!!

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
How is this different than #72?

**Comment by paulstey** [comment]
@mcmcgrath13: Excellent question!! This version includes substantially more snow!!

This is from last weekend's snowfall, which was massive compared to last months!

**Comment by mcmcgrath13** [comment]
fair enough! my comment on #72 still holds

**Comment by paulstey** [comment]
I think switching base on dates is great, but I would vote not to hold up this PR based on that. After all, it's something we'd only change twice per year.

I'd be interested in a night-time photo that toggles on in the evening and toggles off in the morning. But again, I would vote we shouldn't wait on that.

**Comment by mcmcgrath13** [comment]
I think it's a pretty small piece of logic worth implementing now.

add a `:style={'--ccv-image': <check date> ? <path-to-winter> : <path-to-summer>}` on the hero element, then replace the url in the styles with `var(--cv-image)`

**Review by mirestrepo — APPROVED** [review]

**Review by ashleysyg — APPROVED** [review]

**Pull request merged**
