### PR TITLE
feat: add multiple search bars

### PR DESCRIPTION
**Pull request by ashleysyg**
- [x]  added and formatted search bars (feedback on formatting would be appreciated)
- [x] fix issue where when you select a tag from one dropdown, all dropdowns get populated with the tag
- [x] add inactive tag
- [x] change prompts inside filter dropdowns to display tags, departments, languages, etc.
- [x] dropdown logic
- [x] one or multiple clear filter buttons?
- [x] dropdown order to departments first and tags last
- [x] add dropdown titles outside of dropdown 
- [x] human readable dropdown options
- [x] fix: removing tags from dropdown behavior
- [x] fix: each dropdown does not work independently - they all have to selected in order currently
- [x] computational biology is a department and a tag - is this desireable?
- [x] mobile view needs flexbox

### CODE REVIEW

**Review by mirestrepo — COMMENTED** [review]
This is great! I'm asking others what they think about the current behavior... my expectation was to AND the tags, but let's see what others think

**Comment by eldu** [comment]
Here's an annotated screenshot of what I had expected when trying to use the filters.

- **Each individual multi-select dropdown acts as an OR operator within the dropdown.** This did happen! 
- **Each dropdown along with another dropdown is an AND operator.** Looks like it's implemented as a OR operator at the moment.
- **The clear filter button next to the dropdown only clears that dropdown and be renamed to "Clear Filter" making it singular**, instead of 3 buttons that clear all the filters. Another suggestion is to just have one button at the end that is "Clear Filters"
- **Subsequent dropdowns to filter it's options based on the previously selected filters.** 
   - I expected the department dropdown to filter down to only departments that had projects from that had the tags from the previous dropdown.
- Also I would have expected departments to be the first dropdown and then tags. Then tags would filter down to only ones relevant after the departments were set.
- Can we have the title of the filter on top of the dropdown? It was easy to forget which category I selected

Nice to haves:
- Department names to have nicer names than the kabob casing like the tags

Screen Shot 2022-09-12 at 4 17 25 PM

**Comment by ashleysyg** [comment]
Thanks Ellen! This all makes sense. Ill implement this feedback next.

**Comment by ashleysyg** [comment]
@mirestrepo do you think there should be one or three clear filter buttons?

**Comment by eldu** [comment]
> @mirestrepo do you think there should be one or three clear filter buttons?

I think one clear filters button is sufficient since it's easy to remove a dropdown selection in the multiselect. Thoughts?

**Review by mirestrepo — APPROVED** [review]
Looks great! I'm going to also add Ellen as a reviewer just in case she has any comments.

I'm going to make an issue on reducing the choices based on other selections since not all combinations are possible, but that is definitely a nice to have and not part of this PR. So from my side this is ready!

**Comment by mirestrepo** [comment]
@eldu I added you as a reviewer in case you wanted to give a last look! Thank you all!

**Review by eldu — APPROVED** [review]
🚢

**Pull request merged**
