### PR TITLE
feat: dynamic routing for people

### PR DESCRIPTION
**Pull request by ashleysyg**

### CODE REVIEW

**Comment by hetd54** [comment]
Comments:

- Support needed to route for folks without a Github account (Linnea Wolfe, for example)
- Styling for picture leaves spacing if the image is not square (see Aisulu)
- If one's bio is long, your beautiful card gets hidden (see Camilo vs Aisulu); maybe you can decide on a width for the bio instead of having it match its parent?

**Review by hetd54 — CHANGES_REQUESTED** [review]
see comments above regarding styling/edge cases -- code looks good!

**Comment by ashleysyg** [comment]
> * If one's bio is long, your beautiful card gets hidden (see Camilo vs Aisulu); maybe you can decide on a width for the bio instead of having it match its parent?

I'm not seeing this. Aisulu's bio shows up, and Camilo has a blank bio. Is there another example of a long bio that you were seeing issues with?

**Review by eldu — APPROVED** [review]
Oh this looks great !!

**Review by ashleysyg — COMMENTED** [review]
can @hetd54 or @eldu approve these changes and then ill merge :)

**Pull request merged**
