### PR TITLE
fix: add oit to sort order for about page

### PR DESCRIPTION
**Pull request by paulstey**
This is a tiny PR that accompanies the OIT section PR from the `-content` repo. In particular, it adds `oit` to the sorting order of section in the `About` page.

### CODE REVIEW

**Review by mirestrepo — CHANGES_REQUESTED** [review]
You also need to add an entry to the NavBar :)

**Comment by paulstey** [comment]
@mirestrepo : Good catch!! The latest push should fix that!

Thank you, Isa!!

**Comment by paulstey** [comment]
Ooops... still borked. Hold please.

**Review by mirestrepo — APPROVED** [review]

**Comment by mirestrepo** [comment]
@paulstey actually while you are at it, do you mind fixing the links for About in the footer? They don't correspond to the existing sections I think ... there are no - Statements

**Comment by mirestrepo** [comment]
I think Ashley has the footer fixes in another PR, so you could merge this as is!

**Pull request merged**
