### PR TITLE
feat: adds about menu

### LINKED ISSUE #81: style: icon spacing and menu
- [ ] The spacing between iron and section header is too small
- [ ] Add sections to the Menu 

image

### PR DESCRIPTION
**Pull request by mirestrepo**
This PR resolves #81 

- [x] Increases spacing between icon and title in `About` sections - which is now consitent with other places in website
- [x] Adds navbar items to `About`

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
I tried to use one of the nav links, but it doesn't seem to actually go to the place on the page on a fresh page load.

Go to home page > hover on about > click facilities statement > goes to top of about page

once I'm on the about page, it seems to work as expected though

**Comment by mirestrepo** [comment]
Yes, that happens with all links of that type ... not just from the nav bar. So for instance if we have links to in the other sections of the website to a subsection, the same happens. I was going to make an issue about it. But I don't think the navbar is the problem?

**Comment by mcmcgrath13** [comment]
https://github.com/nuxt/nuxt.js/issues/5359 seems related

**Comment by mirestrepo** [comment]
ughh.. do we try [this](https://github.com/nuxt/nuxt.js/issues/5359#issuecomment-887844544)?

**Comment by mirestrepo** [comment]
That will fix it for the nav - but won't fix it for embedded links in the markdown content that try to use a `#` link - the visualization systems has a link to Oscar section that doesn't work

**Comment by mcmcgrath13** [comment]
I think the root issue might be that the content (and therefore anchor) doesn't quite exist upon navigation due to the javascript generating it, so I'm not sure that would fix it.  Have you tried it?

**Comment by mirestrepo** [comment]
okay - I tried [this](https://github.com/nuxt/nuxt.js/issues/5359#issuecomment-475918374) workaround and it seemed to work locally at least. We'll see

**Comment by mirestrepo** [comment]
I lied - it doesn't work 😭. So what do we do?

**Comment by mirestrepo** [comment]
Okay - [this](https://github.com/nuxt/nuxt.js/issues/5359#issuecomment-475961031) worked locally. Let's see 🤞

**Review by paulstey — APPROVED** [review]

**Comment by paulstey** [comment]
🕺

**Pull request merged**
